#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "nord"
    colorscheme_bg = "dark"
    #font
    #guifont = "SauceCodePro Nerd Font Mono:h8"
    guifont = "Hack NF:h9"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_iseparator = "bar"
    statusline_inactive_separator = "fire"
    statusline_separator = 'fire'
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    statusline_unicode_symbols = false
    #File manager (NERDtree)
    filemanager = "nerdtree"
    #YouCompleteMe
    autocomplete_method = "neocomplete"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "nil"
  auto_completion_tab_key_behavior = "smart"
  auto_completion_delay = 20
  auto_completion_complete_with_key_sequence = "nil"
  auto_completion_complete_with_key_sequence_delay = 0.1

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 30

[[layers]]
  name = "lang#python"
  enable_typeinfo = true
  python_interpreter = "C:\Users\saulo\AppData\Local\Programs\Python\Python38-32\python.exe"  

[[layers]]
  name = "lsp"
  filetypes = [
  "css",
  "python",
  "html",
  "javascript"
  ]
  [layers.override_cmd]
    css = ['clangd']
    html = ['html-languageserver', '--stdio']
    python = ['pyls']
    javascript = ['javascript-typescript-stdio']

[[layers]]
    name = "incsearch"

[[layers]]
  name = "core#statusline"

[[layers]]
  name = "lang#dart"

[[layers]]
  name = "lang#typescript"

[[layers]]
  name = "lang#javascript"

[[custom_plugins]]
  repo = "mhartington/oceanic-next"
  merged = 0

[[custom_plugins]]
  repo = "ryanoasis/vim-devicons"

[[custom_plugins]]
  repo = "Shougo/neosnippet-snippets"

[[custom_plugins]]
  repo = "honza/vim-snippets"

[[custom_plugins]]
  repo = "arcticicestudio/nord-vim"

[[custom_plugins]]
  repo = "Shougo/defx.nvim"


